name: Run Terraform
description: 'Run Terraform'
inputs:  
  cloudProvider:
    description: 'Cloud Provider'
    type: string
  regionName:
    description: 'Region'
    type: string
  tfAction:
    description: 'TF Action'
    type: string  

runs:
  using: "composite"
  steps:
  - name: Prepare Vars
    id: vars
    uses: actions/github-script@v7
    with:
      script: |
        regionName = "${{ inputs.regionName }}"
        regionZone = ""

        checkRegion = "${{ inputs.regionName }}".match(/-[abc]$/)       
        if(checkRegion){
          regionZone = "${{ inputs.regionName }}"
          regionName = "${{ inputs.regionName }}".replaceAll(checkRegion[0], "")
        }
        
        core.setOutput("regionName", regionName)
        core.setOutput("regionZone", regionZone)
        core.setOutput("vmSize", JSON.parse(JSON.stringify(${{ vars.VM_SIZE_MAP }}))[regionName])
        
  - name: Setup TF Vars
    shell: bash
    run: |
      cd iac/arc_infra/${{ inputs.cloudProvider }}
      sed -i 's/{PREFIX}/${{ vars.RESOURCE_PREFIX }}/g' terraform.tfvars
      sed -i 's/{REGION}/${{ steps.vars.outputs.regionName }}/g' terraform.tfvars
      sed -i 's/{REGION_ZONE}/${{ steps.vars.outputs.regionZone }}/g' terraform.tfvars
      sed -i 's/{PROJECT_ID}/${{ vars.GCP_PROJECT_ID }}/g' terraform.tfvars
      sed -i 's/{VM_SIZE}/${{ steps.vars.outputs.vmSize }}/g' terraform.tfvars
      cat terraform.tfvars

  - name: Get Runner IP
    if: inputs.cloudProvider == 'azure'
    shell: bash
    run: |
      IP=$(curl -sL https://api.ipify.org)
      echo "RUNNER_IP=$IP" >> $GITHUB_ENV
  
  - name: Whitelist Runner IP
    if: inputs.cloudProvider == 'azure'
    uses: azure/CLI@v1
    with:
      inlineScript: |
        echo "Whitelisting Runner IP"
        az storage account update --name ${{ env.STORAGE_ACCOUNT_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --public-network-access Enabled
        az storage account network-rule add --account-name ${{ env.STORAGE_ACCOUNT_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --ip-address ${{ env.RUNNER_IP }}
        echo "Propagating whitelisting..."
        sleep 30
    
    # Terraform Steps
  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3
    with:
      terraform_version: ${{ env.TERRAFORM_VERSION }}
  
  - name: Export Token as TF Var
    shell: bash
    run: echo "TF_VAR_gh_token=${{ env.GH_TOKEN }}" >> $GITHUB_ENV
  
  - name: Export GH Token
    shell: bash
    run: |
      cd iac/arc_infra/${{ inputs.cloudProvider }}
      terraform init
      terraform plan
      if [[ "${{ inputs.tfAction }}" == "apply" ]]; then
        terraform apply -auto-approve
      elif [[ "${{ inputs.tfAction }}" == "destroy" ]]; then
        terraform destroy -auto-approve
      fi