name: Install ARC
run-name: Install ARC
on:
  workflow_call:
    inputs:
      CLOUD_PROVIDER:
        description: "Cloud Provider"
        type: string
      REGION:
        description: "Region (Location)"
        type: string

jobs:
  install_arc:
    name: Install Arc
    runs-on: [ubuntu-latest]
    environment: ${{ inputs.CLOUD_PROVIDER }}
    env:
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      GH_INSTALLATION_ID: ${{ secrets.GH_INSTALLATION_ID }}
      OWNER_NAME: kgacdevops
      CLUSTER_NAME: "${{ vars.RESOURCE_PREFIX }}-cluster"
    steps:
    - name: Generate GH Token
      uses: kgacdevops/github_automation_scripts/.github/actions/generateGithubToken@main

    - name: Validate Inputs
      id: vars
      uses: actions/github-script@v7
      with:
        script: |
          regionName = "${{ inputs.REGION }}"
          regionZone = ""
          checkRegion = "${{ inputs.REGION }}".match(/-[abc]$/)    
          if(checkRegion){
            regionZone = "${{ inputs.REGION }}"
            regionName = "${{ inputs.REGION }}".replaceAll(checkRegion[0], "")
          }
          if(!(JSON.parse(JSON.stringify(${{ vars.VM_SIZE_MAP }})).hasOwnProperty(regionName))){
            core.setFailed("No resources provisioned for the region provided: " + regionName)
          }
          core.setOutput("regionZone", regionZone)

    - name: Checkout CICD Repository
      uses: actions/checkout@v4
      with:
        repository: kgacdevops/cicd_arc
        ref: main
        path: cicd
    
    - name: Setup Github PEM
      shell: bash
      run: printf '%s\n' "${{ env.GH_APP_PRIVATE_KEY }}" > github_app_key.pem

    - name: Setup up Google Cloud Auth
      if: inputs.CLOUD_PROVIDER == 'gcp'
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/${{ vars.GCP_PROJECT_NUM }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "${{ vars.SVC_ACCOUNT }}@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

    - name: Install GKE Auth Plugin
      if: inputs.CLOUD_PROVIDER == 'gcp'
      uses: "google-github-actions/setup-gcloud@v2"
      with:
        install_components: "gke-gcloud-auth-plugin"
      
    - name: Authenticate to GKE cluster
      if: inputs.CLOUD_PROVIDER == 'gcp'
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.CLUSTER_NAME }}
        location: ${{ steps.vars.outputs.regionZone }}
    
    - name: Setup Azure Auth
      if: inputs.CLOUD_PROVIDER == 'azure'
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}    
    
    - name: Install Helm
      if: inputs.CLOUD_PROVIDER == 'azure'
      uses: azure/setup-helm@v4
    
    - name: Install Arc - Azure
      if: inputs.CLOUD_PROVIDER == 'azure'
      shell: bash
      env:
        RESOURCE_GROUP_NAME: "${{ vars.RESOURCE_PREFIX }}-aks-rg"
      run: |
        az account set --subscription ${{ vars.AZURE_SUBSCRIPTION_ID }}
        az aks command invoke --resource-group "${{ env.RESOURCE_GROUP_NAME }}" --name "${{ env.CLUSTER_NAME }}" --file "cicd/scripts/setup_arc.sh" --file "github_app_key.pem" --command "GH_APP_ID=${{ env.GH_APP_ID }} GH_INSTALLATION_ID=${{ env.GH_INSTALLATION_ID}} bash setup_arc.sh azure"
    
    - name: Install Arc - AWS/GCP
      if: inputs.CLOUD_PROVIDER != 'azure'
      shell: bash
      run: |
        cd cicd/scripts
        cp ${{ github.workspace }}/github_app_key.pem .
        chmod +x setup_arc.sh
        ./setup_arc.sh ${{ inputs.CLOUD_PROVIDER }}