name: Install Pre-reqs
run-name: Install Pre-reqs
on:
  workflow_call:
    inputs:
      CLOUD_PROVIDER:
        description: "Cloud Provider"
        type: string
      REGION:
        description: "Region (Location)"
        type: string

jobs:
  install_prereq_gcp:
    name: Install PreReqs - GCP
    if: inputs.CLOUD_PROVIDER == 'gcp'
    runs-on: [ubuntu-latest]
    environment: ${{ inputs.CLOUD_PROVIDER }}
    steps:
    - name: Checkout CICD Repository
      uses: actions/checkout@v4
      with:
        repository: kgacdevops/cicd_arc
        ref: main
        path: cicd

    - name: Setup up Google Cloud Auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/${{ vars.GCP_PROJECT_NUM }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "devops-svc-account@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
    
    - name: Setup Pre-requisites
      shell: bash
      run: |
        cd cicd/scripts/bash
        chmod ugo+rwx setup_prereq_gcp.sh
        ./setup_prereq_gcp.sh "${{ vars.GCP_PROJECT_ID }}" "${{ vars.GCP_PROJECT_NUM }}" "${{ inputs.REGION }}"
  
  install_prereq_azure:
    name: Install PreReqs - Azure
    if: inputs.CLOUD_PROVIDER == 'azure'
    runs-on: [ubuntu-latest]
    environment: ${{ inputs.CLOUD_PROVIDER }}
    steps:
    - name: Checkout CICD Repository
      uses: actions/checkout@v4
      with:
        repository: kgacdevops/cicd_arc
        ref: main
        path: cicd

    - name: Setup Azure Auth
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
    
    - name: Setup Pre-Requisites
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          cd cicd/scripts/bash
          chmod ugo+rwx setup_prereq_azure.sh
          ./setup_prereq_azure.sh "${{ inputs.REGION }}"